Fixed Broken Link
kubevirt/kubevirt-tutorial pull request #118
Opened 2021-04-05 18:11 UTC by ansijain

Signed-off-by: ansijain <ansi.jain@india.nec.com>

2021-04-05 18:56 UTC, mazzystr commented
/approve
/lgtm

Thanks for the fixes!

2021-04-05 18:56 UTC, mazzystr commented
/ok-to-test

2021-04-08 02:23 UTC, ansijain commented
Fixed one more link 
@mazzystr can you please have a look

2021-04-09 16:54 UTC, mazzystr requested changes

2021-04-09 16:54 UTC, mazzystr commented on labs/lab000/lab000.md
> +- [KubeVirt user guide](https://kubevirt.io/user-guide/welcome/)
Can you change to simply `https://kubevirt.io/user-guide`? [user-guide/pull/425](https://github.com/kubevirt/user-guide/pull/425) is going to remove the `welcome` uri

2021-04-09 17:07 UTC, mazzystr commented
Thanks!

/approve
/lgtm

2021-04-09 17:10 UTC, mazzystr approved these changes

2021-04-20 08:18 UTC, ansijain commented
/retest

2021-04-30 09:13 UTC, ansijain commented
@mazzystr Can you please have a look and let me know what should I do
as test is failing and giving error ERROR: This script does not work on Python 3.5 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/pip/3.5/get-pip.py instead.

2021-06-22 08:16 UTC, ansijain commented
/retest

2021-06-22 08:41 UTC, merged